In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [5]:
df = pd.read_csv(r'd:\00 - Woxsen\MBA (Business Analytics)\Term 3 - Subjects\Machine Learning for Business\03Mar25\50_Startups_EDA.csv')

In [7]:
df.nunique

<bound method DataFrame.nunique of     R&D Spend      Sales  Administration  Marketing Spend       State  \
0   210983.00  210983.00        20938.00           635.00     Chennai
1   327849.00  327849.00        28746.00           948.00     Chennai
2   210983.00  210983.00        20938.00              NaN     Chennai
3   327849.00  327849.00             NaN           948.00     Chennai
4   165349.20  165349.20       136897.80        471784.10     Chennai
5   162597.70  162597.70       151377.59        443898.53      Trichy
6   153441.51  153441.51       101145.55        407934.54  Coimbatore
7   144372.41  144372.41       118671.85        383199.62     Chennai
8   142107.34  142107.34        91391.77        366168.42  Coimbatore
9   142107.34  142107.34        91391.77        366168.42  Coimbatore
10  134615.46  134615.46       147198.87        127716.82      Trichy
11  131876.90  131876.90        99814.71        362861.36     Chennai
12  130298.13  130298.13       145530.06        323876.68  Coimbatore
13  123334.88  123334.88       108679.17        304981.62      Trichy
14  120542.52  120542.52       148718.95        311613.29     Chennai
15  119943.24  119943.24       156547.42        256512.92  Coimbatore
16  114523.61  114523.61       122616.84        261776.23     Chennai
17  101913.08  101913.08       110594.11        229160.95  Coimbatore
18  100671.96  100671.96        91790.61        249744.55      Trichy
19   94657.16   94657.16       145077.58        282574.31     Chennai
20   93863.75   93863.75       127320.38        249839.44  Coimbatore
21   91992.39   91992.39       135495.07        252664.93      Trichy
22   91749.16   91749.16       114175.79        294919.57  Coimbatore
23   86419.70   86419.70       153514.11             0.00     Chennai
24   78389.47   78389.47       153773.43        299737.29     Chennai
25   78013.11   78013.11       121597.55        264346.06      Trichy
26   77044.01   77044.01        99281.34        140574.81     Chennai
27   76253.86   76253.86       113867.30        298664.47      Trichy
28   75328.87   75328.87       144135.98        134050.07  Coimbatore
29   75328.87   75328.87       144135.98        134050.07  Coimbatore
30   73994.56   73994.56       122782.75        303319.26  Coimbatore
31   72107.60   72107.60       127864.55        353183.81     Chennai
32   67532.53   67532.53       105751.03        304768.73  Coimbatore
33   66051.52   66051.52       182645.56        118148.20  Coimbatore
34   65605.48   65605.48       153032.06        107138.38     Chennai
35   64664.71   64664.71       139553.16        137962.62      Trichy
36   64664.71   64664.71       139553.16        137962.62      Trichy
37   63408.86   63408.86       129219.61         46085.25      Trichy
38   61994.48   61994.48       115641.28         91131.24  Coimbatore
39   61136.38   61136.38       152701.92         88218.23     Chennai
40   55493.95   55493.95       103057.49        214634.81  Coimbatore
41   46426.07   46426.07       157693.92        210797.67      Trichy
42   46014.02   46014.02        85047.44        205517.64     Chennai
43   44069.95   44069.95        51283.14        197029.42      Trichy
44   38558.51   38558.51        82982.09        174999.30      Trichy
45   28754.33   28754.33       118546.05        172795.67      Trichy
46   28663.76   28663.76       127056.21        201126.82  Coimbatore
47   27892.92   27892.92        84710.77        164470.71  Coimbatore
48   23640.93   23640.93        96189.63        148001.11      Trichy
49   22177.74   22177.74       154806.14         28334.72      Trichy
50   20229.59   20229.59        65947.93        185265.10     Chennai
51   15505.73   15505.73       127382.30         35534.17     Chennai
52   15505.73   15505.73       127382.30         35534.17     Chennai
53   15505.73   15505.73       127382.30         35534.17     Chennai
54   15505.73   15505.73       127382.30         35534.17     Chennai
55    1315.46    1315.46       115816.21        297114.46  Coimbatore
56    1000.23    1000.23       124153.04          1903.93     Chennai
57     542.05     542.05        51743.15             0.00     Chennai
58        NaN        NaN       135426.92              NaN      Trichy
59       0.00       0.00       116983.80         45173.06      Trichy

       Profit
0   210937.00
1   384664.00
2   210937.00
3   384664.00
4   192261.83
5   191792.06
6   191050.39
7   182901.99
8   166187.94
9   166187.94
10  156122.51
11  156991.12
12  155752.60
13  149759.96
14  152211.77
15  132602.65
16  129917.04
17  146121.95
18  144259.40
19  125370.37
20  141585.52
21  134307.35
22  124266.90
23  122776.86
24  111313.02
25  126992.93
26  108552.04
27  118474.03
28  105733.54
29  105733.54
30  110352.25
31  105008.31
32  108733.99
33  103282.38
34  101004.64
35  107404.34
36  107404.34
37   97427.84
38   99937.59
39   97483.56
40   96778.92
41   96712.80
42   96479.51
43   89949.14
44   81005.76
45   78239.91
46   90708.19
47   77798.83
48   71498.49
49   65200.33
50   81229.06
51   69758.98
52   69758.98
53   69758.98
54   69758.98
55   49490.75
56   64926.08
57   35673.41
58   42559.73
59   14681.40  >

In [8]:
df.columns

Index(['R&D Spend', 'Sales', 'Administration', 'Marketing Spend', 'State',
       'Profit'],
      dtype='object')